version: "3.3"  
services:
  sensors-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=/tmp/raizen-challenge-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fluffy
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE 
    healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
            timeout: 20s
            retries: 10
    volumes:
    - ./sensors-database/:/tmp/raizen-challenge-db/
    - ./sensors-database/createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
  sensors-service:
    image: sensors-service
    ports:
      - 8000:8000
    depends_on:
      sensors-db:
        condition: service_healthy