openapi: 3.0.0
info:
  title: Sensors Challenge API
  description: Sensors API
  version: 0.0.1
servers:
  - url: http://localhost:8000/sensors/v1
security:
 - basicAuth: []
tags: 
  - name: Sensors Data
    description: Gets the sensors data
paths:
  /data:
    get:
      tags: 
        - Sensors Data
      summary: Returns the sensors data using the request parameters to limit the number of results
      parameters:
        - in: query
          name: sort-by
          schema:
            type: string
          example: CO2:ASC, Temp:DSC
        - in: query
          name: range
          schema:
            type: string
            example: 10-01-2020:10-31-2020
        - in: query
          name: limit
          schema:
            type: number
            format: int
            example: 10
      responses:
        '200':    
          description: JSON containing a set of sensors data 
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Data'
        '404':
          description: Service not available
        '5XX':
          description: Internal server error
components:
  schemas:
    Data:
      properties:
        time:
          type: string
          example: "2015-08-06 16:29:40"
        temp:
          type: number
          format: double
          example: 35.0
        co2:
          type: number
          format: double
          example: 2000
        humidity:
          type: number
          format: double
          example: 34.0
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic  
        

