openapi: 3.0.0
info:
  title: Sensors Challenge API
  description: Sensors API
  version: 0.0.1
servers:
  - url: http://localhost:8000/sensors/v1
tags: 
  - name: Sensors Data
    description: Gets the sensors data
paths:
  /data:
    get:
      tags: 
        - Sensors Data
      summary: Returns the sensors data using the request parameters to limit the number of results.
      description: |
        The format is **field:order**, where order can be `DSC` for descending sort or `ASC` for ascending sort
        The available fields are: 
          - time
          - temp 
          - co2 
          - humidity 
      parameters:
        - in: query
          name: sort-by
          description: Specifies the field used for the sorting and the order (ascending or descending)
          schema:
            type: string
          example: co2:ASC
        - in: query
          name: range
          description: Specifies the field and range of data to be fetched (a range of data like numbers or dates)
          schema:
            type: string
            example: time:2015-08-06:2015-08-07
        - in: query
          name: limit
          description: Specify the maximum number of results returned by the service.If no limit is specified it will return 20 entries by default
          schema:
            type: number
            format: int
            example: 10
      responses:
        '200':    
          description: JSON containing a set of sensors data 
          content:
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Data'
        '404':
          description: Service not available
        '5XX':
          description: Internal server error
components:
  schemas:
    Data:
      properties:
        time:
          type: string
          example: "2015-08-06 16:29:40"
        temp:
          type: number
          format: double
          example: 35.0
        co2:
          type: number
          format: double
          example: 2000
        humidity:
          type: number
          format: double
          example: 34.0
        

